/* Flight Stopovers — pick two cities, see every city you could connect
   through, drawn as great-circle arcs on a pan-and-zoom world map.
   Plain script, no dependencies. data.js and map.js are generated by
   build/build-data.js. */
(function () {
  'use strict';

  /* Must match the ?v= stamps and window.FSO_BUILD in index.html. Bump all of
     them whenever app.js, styles.css, data.js or map.js changes. */
  var BUILD = '2026-09-26';

  var D = window.FSO_DATA, M = window.FSO_MAP;
  var $ = function (id) { return document.getElementById(id); };
  var SVGNS = 'http://www.w3.org/2000/svg';
  var EARTH_KM = 6371;
  var RAD = Math.PI / 180;
  var reduceMotion = window.matchMedia && matchMedia('(prefers-reduced-motion: reduce)').matches;

  checkBuild();
  if (!D || !M) return;

  /* ---------- Data ---------- */

  var cities = D.cities.map(function (c, i) {
    return { i: i, name: c[0], country: c[1], ap: [], deg: 0 };
  });
  var airports = D.airports.map(function (a, i) {
    var la = a[3] * RAD, lo = a[4] * RAD;
    cities[a[2]].ap.push(i);
    return {
      i: i, iata: a[0], name: a[1], city: a[2], lat: a[3], lon: a[4],
      v: [Math.cos(la) * Math.cos(lo), Math.cos(la) * Math.sin(lo), Math.sin(la)]
    };
  });
  // adj[i]: Map(neighbour airport index -> [airline indices])
  var adj = D.adj.map(function (s) {
    var m = new Map();
    if (s) s.split(',').forEach(function (e) {
      var p = e.split(':');
      m.set(parseInt(p[0], 36), p[1] ? p[1].split('.').map(function (x) { return parseInt(x, 36); }) : []);
    });
    return m;
  });
  airports.forEach(function (a) { a.deg = adj[a.i].size; });
  cities.forEach(function (c) {
    c.ap.sort(function (x, y) { return airports[y].deg - airports[x].deg; });
    c.deg = c.ap.reduce(function (s, i) { return s + airports[i].deg; }, 0);
    c.main = airports[c.ap[0]];
  });

  function norm(s) {
    return s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase();
  }
  var index = cities.map(function (c) {
    return {
      name: norm(c.name),
      words: norm(c.name).split(/[\s\-/]+/),
      country: norm(c.country),
      codes: c.ap.map(function (i) { return airports[i].iata; }),
      apNames: norm(c.ap.map(function (i) { return airports[i].name; }).join(' | '))
    };
  });

  function angle(a, b) {
    var d = a.v[0] * b.v[0] + a.v[1] * b.v[1] + a.v[2] * b.v[2];
    return Math.acos(Math.max(-1, Math.min(1, d)));
  }
  function km(i, j) { return angle(airports[i], airports[j]) * EARTH_KM; }

  /* ---------- Search ---------- */

  function search(q) {
    var qn = norm(q.trim());
    var qu = q.trim().toUpperCase();
    var hits = [];
    cities.forEach(function (c, i) {
      if (!c.deg) return;
      var x = index[i], s = 0;
      if (!qn) s = 1;
      else if (qu.length === 3 && x.codes.indexOf(qu) >= 0) s = 1000;
      else if (x.name === qn) s = 900;
      else if (x.name.indexOf(qn) === 0) s = 700;
      else if (x.words.some(function (w) { return w.indexOf(qn) === 0; })) s = 500;
      else if (qn.length > 2 && x.name.indexOf(qn) >= 0) s = 300;
      else if (qn.length > 2 && x.apNames.indexOf(qn) >= 0) s = 200;
      else if (qn.length > 2 && x.country.indexOf(qn) === 0) s = 100;
      if (s) hits.push({ c: c, s: s + Math.log(c.deg + 1) * 12 });
    });
    hits.sort(function (a, b) { return b.s - a.s; });
    return hits.slice(0, 8).map(function (h) { return h.c; });
  }

  function cityLabel(c) { return c.name + ', ' + c.country; }

  function Combo(input, list, onPick) {
    var items = [], active = -1, current = null;

    function open(q) {
      items = search(q);
      active = items.length ? 0 : -1;
      list.innerHTML = '';
      if (!items.length) {
        list.innerHTML = '<li class="empty">No city or airport matches that</li>';
      }
      items.forEach(function (c, k) {
        var li = document.createElement('li');
        li.id = input.id + '-opt-' + k;
        li.setAttribute('role', 'option');
        li.innerHTML = '<span><span class="nm"></span> <span class="ct"></span></span><span class="codes"></span>';
        li.querySelector('.nm').textContent = c.name;
        li.querySelector('.ct').textContent = c.country;
        li.querySelector('.codes').textContent = c.ap.slice(0, 3).map(function (i) { return airports[i].iata; }).join(' ');
        li.addEventListener('mousedown', function (e) { e.preventDefault(); });
        li.addEventListener('click', function () { pick(c); });
        list.appendChild(li);
      });
      list.hidden = false;
      input.setAttribute('aria-expanded', 'true');
      mark();
    }
    function close() {
      list.hidden = true;
      input.setAttribute('aria-expanded', 'false');
      input.removeAttribute('aria-activedescendant');
    }
    function mark() {
      [].forEach.call(list.children, function (li, k) { li.setAttribute('aria-selected', k === active ? 'true' : 'false'); });
      if (active >= 0) {
        input.setAttribute('aria-activedescendant', input.id + '-opt-' + active);
        list.children[active].scrollIntoView({ block: 'nearest' });
      }
    }
    function pick(c, silent) {
      current = c;
      input.value = c ? cityLabel(c) : '';
      close();
      if (!silent) { input.blur(); onPick(c); }
    }

    input.addEventListener('focus', function () { input.select(); open(''); });
    input.addEventListener('input', function () { open(input.value); });
    input.addEventListener('blur', function () {
      close();
      input.value = current ? cityLabel(current) : '';
    });
    input.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
        e.preventDefault();
        if (list.hidden) return open(input.value);
        if (!items.length) return;
        active = (active + (e.key === 'ArrowDown' ? 1 : items.length - 1)) % items.length;
        mark();
      } else if (e.key === 'Enter') {
        e.preventDefault();
        if (items[active]) pick(items[active]);
      } else if (e.key === 'Escape') {
        input.blur();
      }
    });

    return {
      get: function () { return current; },
      set: function (c) { pick(c, true); }
    };
  }

  /* ---------- Route finding ---------- */

  // Every way to get from city o to city t with up to maxStops connections,
  // keeping the shortest itinerary per stopover city (or pair of cities).
  function findOptions(o, t, maxStops, maxRatio) {
    var O = cities[o], T = cities[t];
    var skip = function (c) { return c === o || c === t; };

    // Airports with a non-stop flight into the destination, and the closest
    // destination airport each one reaches.
    var intoT = new Map();
    T.ap.forEach(function (b) {
      adj[b].forEach(function (_, y) {
        var d = km(y, b), cur = intoT.get(y);
        if (!cur || d < cur.d) intoT.set(y, { b: b, d: d });
      });
    });

    var direct = [], one = new Map(), two = new Map();
    O.ap.forEach(function (a) {
      T.ap.forEach(function (b) {
        if (adj[a].has(b)) direct.push({ stops: [a, b], km: km(a, b) });
      });
      adj[a].forEach(function (_, x) {
        var cx = airports[x].city;
        if (skip(cx)) return;
        var d1 = km(a, x);
        var n = intoT.get(x);
        if (n) {
          var tot = d1 + n.d, cur = one.get(cx);
          if (!cur || tot < cur.km) one.set(cx, { stops: [a, x, n.b], km: tot });
        }
        if (maxStops < 2) return;
        adj[x].forEach(function (_, y) {
          var cy = airports[y].city;
          if (cy === cx || skip(cy)) return;
          var m = intoT.get(y);
          if (!m) return;
          var tot2 = d1 + km(x, y) + m.d;
          if (tot2 > maxRatio * km(a, m.b)) return;
          var key = cx * 65536 + cy, cur2 = two.get(key);
          if (!cur2 || tot2 < cur2.km) two.set(key, { stops: [a, x, y, m.b], km: tot2 });
        });
      });
    });

    function finish(list) {
      return list.map(decorate)
        .filter(function (r) { return r.ratio <= maxRatio + 1e-9; })
        .sort(function (a, b) { return a.km - b.km; });
    }
    return {
      direct: finish(direct),
      one: finish(Array.from(one.values())),
      two: maxStops >= 2 ? finish(Array.from(two.values())) : []
    };
  }

  function decorate(r) {
    var s = r.stops;
    r.straight = km(s[0], s[s.length - 1]);
    r.ratio = r.straight ? r.km / r.straight : 1;
    r.legs = [];
    var common = null;
    for (var k = 1; k < s.length; k++) {
      var als = adj[s[k - 1]].get(s[k]) || [];
      var d = km(s[k - 1], s[k]);
      r.legs.push({ from: s[k - 1], to: s[k], km: d, airlines: als });
      common = common === null ? als.slice() : common.filter(function (x) { return als.indexOf(x) >= 0; });
    }
    r.common = s.length > 2 ? common : [];
    r.hours = r.legs.reduce(function (h, l) { return h + 0.5 + l.km / 830; }, 0);
    r.via = s.slice(1, -1).map(function (i) { return cities[airports[i].city]; });
    return r;
  }

  /* ---------- Map ---------- */

  var svg = $('map');
  var view = { x: 10, y: -20, w: 360 };
  var layers = {};

  function el(tag, attrs, parent) {
    var n = document.createElementNS(SVGNS, tag);
    for (var k in attrs) n.setAttribute(k, attrs[k]);
    if (parent) parent.appendChild(n);
    return n;
  }

  function buildMap() {
    var defs = el('defs', {}, svg);
    el('path', { id: 'fso-land', d: M.land, 'vector-effect': 'non-scaling-stroke' }, defs);
    el('rect', { class: 'ocean', x: -1000, y: -200, width: 2000, height: 400 }, svg);
    var world = el('g', {}, svg);
    var g = '';
    for (var lon = -540; lon <= 540; lon += 30) g += 'M' + lon + ' -85V85';
    for (var lat = -60; lat <= 60; lat += 30) g += 'M-540 ' + lat + 'H540';
    el('path', { class: 'grat', d: g }, world);
    // Three copies of the world side by side, so routes that cross the
    // Pacific can be drawn continuously instead of being cut at ±180°.
    [-360, 0, 360].forEach(function (dx) {
      el('use', { href: '#fso-land', class: 'land', transform: 'translate(' + dx + ' 0)' }, world);
    });
    layers.routes = el('g', {}, svg);
    layers.pins = el('g', {}, svg);
    layers.labels = el('g', {}, svg);
  }

  function size() {
    var r = svg.getBoundingClientRect();
    return { W: Math.max(1, r.width), H: Math.max(1, r.height), left: r.left, top: r.top };
  }

  function clampView(v) {
    var s = size();
    var w = Math.max(3, Math.min(v.w, 520));
    var h = w * s.H / s.W;
    var y = v.y;
    // North to 84°N, south to 78°S (below that is only the Antarctic plateau).
    if (h >= 162) y = -3; else y = Math.max(-84 + h / 2, Math.min(78 - h / 2, y));
    var x = Math.max(-360, Math.min(360, v.x));
    return { x: x, y: y, w: w };
  }

  function applyView() {
    view = clampView(view);
    var s = size();
    var h = view.w * s.H / s.W;
    svg.setAttribute('viewBox', [view.x - view.w / 2, view.y - h / 2, view.w, h].map(function (n) { return n.toFixed(4); }).join(' '));
    var u = view.w / s.W; // degrees per CSS pixel
    [].forEach.call(layers.pins.children, function (p) {
      p.setAttribute('r', (p.classList.contains('end') ? 6 : 4.5) * u);
    });
    [].forEach.call(layers.labels.children, function (t) {
      var end = t.classList.contains('end');
      t.setAttribute('font-size', (end ? 13 : 11.5) * u);
      t.setAttribute('x', +t.dataset.x + 8 * u);
      t.setAttribute('y', +t.dataset.y + 4 * u);
    });
  }

  var anim = 0;
  function animateTo(target) {
    target = clampView(target);
    cancelAnimationFrame(anim);
    if (reduceMotion) { view = target; return applyView(); }
    var from = { x: view.x, y: view.y, w: view.w }, t0 = performance.now();
    (function step(now) {
      var k = Math.min(1, (now - t0) / 450);
      var e = k < 0.5 ? 2 * k * k : 1 - Math.pow(-2 * k + 2, 2) / 2;
      // Interpolate zoom geometrically so the move feels even.
      view = {
        x: from.x + (target.x - from.x) * e,
        y: from.y + (target.y - from.y) * e,
        w: from.w * Math.pow(target.w / from.w, e)
      };
      applyView();
      if (k < 1) anim = requestAnimationFrame(step);
    })(t0);
  }

  function fitBox(b) {
    if (!b) return animateTo({ x: 10, y: -20, w: 360 });
    var s = size();
    var bw = Math.max(b.x1 - b.x0, 6), bh = Math.max(b.y1 - b.y0, 4);
    // Leave room for labels, the zoom buttons and the legend, in pixels.
    var padX = Math.min(130, s.W * 0.4), padY = Math.min(110, s.H * 0.45);
    var w = Math.max(bw * s.W / (s.W - padX), bh * s.H / (s.H - padY) * s.W / s.H);
    var u = w / s.W;
    animateTo({ x: (b.x0 + b.x1) / 2 + 8 * u, y: (b.y0 + b.y1) / 2 + 12 * u, w: w });
  }

  function zoomAt(px, py, f) {
    cancelAnimationFrame(anim);
    var s = size(), u = view.w / s.W, h = view.w * s.H / s.W;
    var wx = view.x - view.w / 2 + px * u, wy = view.y - h / 2 + py * u;
    var w = Math.max(3, Math.min(view.w * f, 520)), u2 = w / s.W, h2 = w * s.H / s.W;
    view = { x: wx - px * u2 + w / 2, y: wy - py * u2 + h2 / 2, w: w };
    applyView();
  }

  // Great-circle arc between two airports as [lon, lat] points, with each
  // longitude unwrapped to sit within 180° of the previous one.
  function arc(i, j, startLon) {
    var a = airports[i], b = airports[j], d = angle(a, b);
    var n = Math.max(2, Math.ceil(d * EARTH_KM / 120));
    var pts = [], prev = startLon;
    for (var k = 0; k <= n; k++) {
      var t = k / n, v;
      if (d < 1e-6) v = a.v;
      else {
        var s1 = Math.sin((1 - t) * d) / Math.sin(d), s2 = Math.sin(t * d) / Math.sin(d);
        v = [s1 * a.v[0] + s2 * b.v[0], s1 * a.v[1] + s2 * b.v[1], s1 * a.v[2] + s2 * b.v[2]];
      }
      var lat = Math.atan2(v[2], Math.sqrt(v[0] * v[0] + v[1] * v[1])) / RAD;
      var lon = Math.atan2(v[1], v[0]) / RAD;
      while (lon - prev > 180) lon -= 360;
      while (lon - prev < -180) lon += 360;
      prev = lon;
      pts.push([lon, lat]);
    }
    return pts;
  }

  var drawn = [];    // one entry per option on the map
  var pinsByKey = new Map();

  function drawRoutes(opts) {
    layers.routes.innerHTML = layers.pins.innerHTML = layers.labels.innerHTML = '';
    pinsByKey.clear();
    drawn = [];
    var labelStops = opts.length <= 30;

    opts.forEach(function (r, n) {
      var s = r.stops, lon = airports[s[0]].lon, d = '', keys = [];
      var box = { x0: Infinity, x1: -Infinity, y0: Infinity, y1: -Infinity };
      for (var k = 0; k < s.length; k++) {
        var ap = airports[s[k]];
        var x = ap.lon + 360 * Math.round((lon - ap.lon) / 360);
        keys.push(pin(ap, x, k === 0 || k === s.length - 1, labelStops));
        if (k === s.length - 1) break;
        var pts = arc(s[k], s[k + 1], x);
        pts.forEach(function (p, m) {
          d += (m ? 'L' : 'M') + p[0].toFixed(2) + ' ' + (-p[1]).toFixed(2);
          box.x0 = Math.min(box.x0, p[0]); box.x1 = Math.max(box.x1, p[0]);
          box.y0 = Math.min(box.y0, -p[1]); box.y1 = Math.max(box.y1, -p[1]);
        });
        lon = pts[pts.length - 1][0];
      }
      var g = el('g', { class: 'route' + (s.length === 2 ? ' direct' : ''), 'data-n': n }, layers.routes);
      el('path', { class: 'hit', d: d }, g);
      el('path', { class: 'vis', d: d }, g);
      drawn.push({ r: r, g: g, keys: keys, box: box });
    });
    // Direct flights on top of the stopover web.
    drawn.forEach(function (x) { if (x.r.stops.length === 2) layers.routes.appendChild(x.g); });
    applyView();
  }

  function pin(ap, x, end, withLabel) {
    var key = ap.city + '@' + Math.round((x - ap.lon) / 360);
    var have = pinsByKey.get(key);
    if (have) {
      if (end && !have.end) {
        have.end = true;
        [have.p, have.t].forEach(function (n) { n.classList.add('end'); n.classList.remove('stop', 'faint'); });
      }
      return key;
    }
    var c = cities[ap.city], cls = end ? 'end' : 'stop';
    var p = el('circle', { class: 'pin ' + cls, cx: x, cy: -ap.lat, r: 0.5 }, layers.pins);
    var t = el('text', { class: 'lbl ' + cls + (end || withLabel ? '' : ' faint'), 'data-x': x, 'data-y': -ap.lat }, layers.labels);
    t.textContent = c.name;
    var title = el('title', {}, p);
    title.textContent = c.name + ' (' + ap.iata + ')';
    pinsByKey.set(key, { p: p, t: t, end: end });
    return key;
  }

  function markMap(n, cls, on) {
    var x = drawn[n];
    if (!x) return;
    x.g.classList.toggle(cls, on);
    if (on) layers.routes.appendChild(x.g);
    x.keys.forEach(function (k) {
      var pt = pinsByKey.get(k);
      pt.p.classList.toggle(cls, on);
      pt.t.classList.toggle(cls, on);
      if (on) { layers.pins.appendChild(pt.p); layers.labels.appendChild(pt.t); }
    });
    svg.classList.toggle('has-sel', !!svg.querySelector('.route.sel'));
  }

  function allBox() {
    if (!drawn.length) return null;
    return drawn.reduce(function (b, x) {
      return {
        x0: Math.min(b.x0, x.box.x0), x1: Math.max(b.x1, x.box.x1),
        y0: Math.min(b.y0, x.box.y0), y1: Math.max(b.y1, x.box.y1)
      };
    }, { x0: Infinity, x1: -Infinity, y0: Infinity, y1: -Infinity });
  }

  /* Pan, pinch and wheel zoom. Pointer capture starts only once a drag is
     under way, so a plain tap still reaches the route under the finger. */
  var pointers = new Map(), dragged = false, lastPinch = null;
  svg.addEventListener('pointerdown', function (e) {
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY, x0: e.clientX, y0: e.clientY });
    dragged = false;
    lastPinch = null;
  });
  svg.addEventListener('pointermove', function (e) {
    var p = pointers.get(e.pointerId);
    if (!p) return hoverTip(e);
    var s = size(), u = view.w / s.W;
    if (pointers.size === 1) {
      if (!dragged && Math.hypot(e.clientX - p.x0, e.clientY - p.y0) < 5) return;
      if (!dragged) { dragged = true; svg.setPointerCapture(e.pointerId); svg.classList.add('dragging'); hideTip(); }
      cancelAnimationFrame(anim);
      view.x -= (e.clientX - p.x) * u;
      view.y -= (e.clientY - p.y) * u;
      p.x = e.clientX; p.y = e.clientY;
      applyView();
    } else if (pointers.size === 2) {
      dragged = true;
      p.x = e.clientX; p.y = e.clientY;
      var q = Array.from(pointers.values());
      var dist = Math.hypot(q[0].x - q[1].x, q[0].y - q[1].y);
      var mx = (q[0].x + q[1].x) / 2 - s.left, my = (q[0].y + q[1].y) / 2 - s.top;
      if (lastPinch) {
        view.x -= (mx - lastPinch.mx) * u;
        view.y -= (my - lastPinch.my) * u;
        zoomAt(mx, my, lastPinch.dist / dist);
      }
      lastPinch = { dist: dist, mx: mx, my: my };
    }
  });
  function endPointer(e) {
    pointers.delete(e.pointerId);
    lastPinch = null;
    if (!pointers.size) svg.classList.remove('dragging');
  }
  svg.addEventListener('pointerup', endPointer);
  svg.addEventListener('pointercancel', endPointer);
  svg.addEventListener('pointerleave', function (e) { if (e.pointerType === 'mouse') hideTip(); });
  svg.addEventListener('wheel', function (e) {
    e.preventDefault();
    var s = size();
    var dy = e.deltaMode === 1 ? e.deltaY * 16 : e.deltaY;
    zoomAt(e.clientX - s.left, e.clientY - s.top, Math.exp(dy * 0.0016));
  }, { passive: false });
  svg.addEventListener('click', function (e) {
    if (dragged) { dragged = false; return; }
    var g = e.target.closest && e.target.closest('.route');
    if (g) select(+g.dataset.n, true);
    else if (selected !== null) select(null);
  });
  $('zoomIn').addEventListener('click', function () { var s = size(); zoomAt(s.W / 2, s.H / 2, 1 / 1.6); });
  $('zoomOut').addEventListener('click', function () { var s = size(); zoomAt(s.W / 2, s.H / 2, 1.6); });
  $('zoomFit').addEventListener('click', function () {
    fitBox(selected !== null ? drawn[selected].box : allBox());
  });

  var tip = $('tip'), hot = null;
  function hoverTip(e) {
    if (e.pointerType !== 'mouse') return;
    var g = e.target.closest && e.target.closest('.route');
    var n = g ? +g.dataset.n : null;
    if (n !== hot) setHot(n);
    if (n === null) return hideTip();
    var s = size();
    tip.textContent = title(drawn[n].r) + ' · ' + fmtKm(drawn[n].r.km);
    tip.hidden = false;
    var x = e.clientX - s.left + 14, y = e.clientY - s.top + 14;
    if (x + tip.offsetWidth > s.W - 8) x = e.clientX - s.left - tip.offsetWidth - 10;
    if (y + tip.offsetHeight > s.H - 8) y = e.clientY - s.top - tip.offsetHeight - 10;
    tip.style.left = x + 'px';
    tip.style.top = y + 'px';
  }
  function hideTip() { tip.hidden = true; if (hot !== null) setHot(null); }

  function setHot(n) {
    if (hot !== null) {
      markMap(hot, 'hot', false);
      var b = listEl.querySelector('.opt[data-n="' + hot + '"]');
      if (b) b.classList.remove('hot');
    }
    hot = n;
    if (n !== null) {
      markMap(n, 'hot', true);
      var b2 = listEl.querySelector('.opt[data-n="' + n + '"]');
      if (b2) b2.classList.add('hot');
      if (selected !== null && selected !== n) markMap(selected, 'sel', true);
    }
  }

  /* ---------- Results list ---------- */

  var listEl = $('list'), summaryEl = $('summary');
  var selected = null, current = null, shownTwo = 0;
  var PAGE = 40;

  function fmtKm(n) { return Math.round(n).toLocaleString() + ' km'; }
  function fmtH(h) {
    var m = Math.round(h * 60 / 5) * 5;
    return Math.floor(m / 60) + 'h ' + String(m % 60).padStart(2, '0') + 'm';
  }
  function code(i) { return airports[i].iata; }
  function airlineNames(als, max) {
    var names = als.map(function (k) { return D.airlines[k][1]; });
    if (!names.length) return 'airline not recorded';
    return names.slice(0, max).join(', ') + (names.length > max ? ' +' + (names.length - max) + ' more' : '');
  }
  function title(r) {
    if (!r.via.length) return 'Direct';
    return 'via ' + r.via.map(function (c) { return c.name; }).join(' & ');
  }
  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; });
  }

  function optionHtml(r, n) {
    var sub = r.via.length
      ? r.via.map(function (c) { return c.country; }).filter(function (x, k, a) { return a.indexOf(x) === k; }).join(' · ')
      : '';
    var meta = [];
    meta.push(r.via.length ? (r.ratio < 1.005 ? 'no detour' : '+' + Math.round((r.ratio - 1) * 100) + '% vs. straight line') : 'shortest way');
    meta.push('≈ ' + fmtH(r.hours) + ' in the air');
    var metaHtml = meta.map(function (m) { return '<span>' + esc(m) + '</span>'; }).join('');
    if (r.common.length) {
      metaHtml += '<span class="one">' + esc(D.airlines[r.common[0]][1]) +
        (r.common.length > 1 ? ' +' + (r.common.length - 1) : '') + ' flies every leg</span>';
    }
    var legs = r.legs.map(function (l) {
      return '<span><b>' + code(l.from) + '→' + code(l.to) + '</b> ' + fmtKm(l.km) +
        ' · <span>' + esc(airlineNames(l.airlines, 4)) + '</span></span>';
    }).join('');
    return '<button type="button" class="opt' + (r.via.length ? '' : ' direct') + '" data-n="' + n + '" aria-pressed="false">' +
      '<span class="t"><span class="via">' + esc(title(r)) + (sub ? ' <small>' + esc(sub) + '</small>' : '') + '</span>' +
      '<span class="km">' + fmtKm(r.km) + '</span></span>' +
      '<span class="path">' + r.stops.map(code).join(' → ') + '</span>' +
      '<span class="meta">' + metaHtml + '</span>' +
      '<span class="legs">' + legs + '</span></button>';
  }

  function render() {
    selected = null; hot = null;
    svg.classList.remove('has-sel');
    var o = fromCombo.get(), t = toCombo.get();
    writeState();
    if (!o || !t) {
      current = null;
      drawRoutes([]);
      listEl.innerHTML = '';
      summaryEl.innerHTML = '';
      showStart();
      return fitBox(null);
    }
    if (o === t) {
      current = null;
      drawRoutes([]);
      listEl.innerHTML = '';
      summaryEl.innerHTML = '<span class="warn">Departure and arrival are the same city — pick a different one.</span>';
      return fitBox(null);
    }
    current = findOptions(o.i, t.i, state.stops, state.detour);
    shownTwo = Math.min(PAGE, current.two.length);
    paint(true);
  }

  function visibleOptions() {
    return current.direct.concat(current.one, current.two.slice(0, shownTwo));
  }

  function paint(fit) {
    var o = fromCombo.get(), t = toCombo.get();
    var opts = visibleOptions();
    drawRoutes(opts);

    var bits = [];
    if (current.direct.length) bits.push(current.direct.length === 1 ? 'a direct flight' : current.direct.length + ' direct flights');
    if (current.one.length) bits.push(current.one.length + ' one-stop option' + (current.one.length === 1 ? '' : 's'));
    if (current.two.length) bits.push(current.two.length.toLocaleString() + ' two-stop option' + (current.two.length === 1 ? '' : 's'));
    var head = '<strong>' + esc(o.name) + ' → ' + esc(t.name) + '</strong> · ' + fmtKm(km(o.main.i, t.main.i)) + ' as the crow flies';
    summaryEl.innerHTML = head + '<br>' + (bits.length
      ? 'Found ' + bits.join(', ') + '. Tap one to highlight it.'
      : '<span class="warn">No connections within that detour.' +
        (state.stops < 2 ? ' Try allowing 2 stops or a larger detour.' : ' Try a larger detour.') + '</span>');

    var html = '', n = 0;
    function group(label, list) {
      if (!list.length) return;
      html += '<li><h2>' + label + '</h2></li>';
      list.forEach(function (r) { html += '<li>' + optionHtml(r, n++) + '</li>'; });
    }
    group('Direct', current.direct);
    group('1 stop', current.one);
    group('2 stops', current.two.slice(0, shownTwo));
    if (shownTwo < current.two.length) {
      html += '<li><button type="button" class="more" id="more">Show ' +
        Math.min(PAGE, current.two.length - shownTwo) + ' more two-stop options (' +
        (current.two.length - shownTwo).toLocaleString() + ' left)</button></li>';
    }
    listEl.innerHTML = html;
    if (fit) fitBox(allBox());
  }

  listEl.addEventListener('click', function (e) {
    if (e.target.id === 'more') {
      shownTwo = Math.min(current.two.length, shownTwo + PAGE);
      return paint(false);
    }
    var b = e.target.closest('.opt');
    if (b) select(+b.dataset.n === selected ? null : +b.dataset.n);
  });
  listEl.addEventListener('mouseover', function (e) {
    var b = e.target.closest('.opt');
    var n = b ? +b.dataset.n : null;
    if (n !== hot) setHot(n);
  });
  listEl.addEventListener('mouseleave', function () { setHot(null); });

  function select(n, fromMap) {
    if (selected !== null) {
      markMap(selected, 'sel', false);
      var old = listEl.querySelector('.opt[data-n="' + selected + '"]');
      if (old) old.setAttribute('aria-pressed', 'false');
    }
    if (n === selected && fromMap) n = null;
    selected = n;
    if (n === null) { svg.classList.remove('has-sel'); return fitBox(allBox()); }
    markMap(n, 'sel', true);
    var b = listEl.querySelector('.opt[data-n="' + n + '"]');
    if (b) {
      b.setAttribute('aria-pressed', 'true');
      if (fromMap) b.scrollIntoView({ block: 'nearest', behavior: reduceMotion ? 'auto' : 'smooth' });
    }
    fitBox(drawn[n].box);
  }

  function showStart() {
    var ex = [['LHR', 'SYD'], ['JFK', 'BKK'], ['CDG', 'HNL'], ['SOF', 'NRT']];
    var html = '<div class="empty-state">Choose a departure and arrival city above. Or try one of these:<br><br>';
    ex.forEach(function (p) {
      var a = cityByCode(p[0]), b = cityByCode(p[1]);
      if (a && b) html += '<button type="button" class="more" style="margin-bottom:6px" data-ex="' + p.join('-') + '">' +
        esc(a.name) + ' → ' + esc(b.name) + '</button>';
    });
    summaryEl.innerHTML = html + '</div>';
  }
  summaryEl.addEventListener('click', function (e) {
    var ex = e.target.dataset && e.target.dataset.ex;
    if (!ex) return;
    var p = ex.split('-');
    fromCombo.set(cityByCode(p[0]));
    toCombo.set(cityByCode(p[1]));
    render();
  });

  /* ---------- Controls and saved state ---------- */

  var state = { stops: 1, detour: 1.5 };
  var fromCombo = Combo($('from'), $('from-list'), function () { render(); if (!toCombo.get()) $('to').focus(); });
  var toCombo = Combo($('to'), $('to-list'), function () { render(); });

  $('swap').addEventListener('click', function () {
    var a = fromCombo.get();
    fromCombo.set(toCombo.get());
    toCombo.set(a);
    render();
  });

  var segBtns = document.querySelectorAll('.seg button');
  function setStops(n) {
    state.stops = n;
    [].forEach.call(segBtns, function (b) { b.setAttribute('aria-checked', +b.dataset.stops === n ? 'true' : 'false'); });
  }
  [].forEach.call(segBtns, function (b) {
    b.addEventListener('click', function () { setStops(+b.dataset.stops); render(); });
  });
  $('detour').addEventListener('change', function (e) { state.detour = +e.target.value; render(); });

  function cityByCode(c) {
    for (var i = 0; i < airports.length; i++) if (airports[i].iata === c) return cities[airports[i].city];
    return null;
  }

  // The trip lives in the URL hash (shareable) and in localStorage (so the
  // app reopens where you left it). Both are optional.
  var KEY = 'flight-stopovers';
  function writeState() {
    var o = fromCombo.get(), t = toCombo.get();
    var p = new URLSearchParams();
    if (o) p.set('from', o.main.iata);
    if (t) p.set('to', t.main.iata);
    p.set('stops', state.stops);
    p.set('detour', state.detour);
    var s = p.toString();
    try { history.replaceState(null, '', '#' + s); } catch (e) { /* ignore */ }
    try { localStorage.setItem(KEY, s); } catch (e) { /* private mode */ }
  }
  function readState() {
    var s = location.hash.slice(1);
    if (!s) { try { s = localStorage.getItem(KEY) || ''; } catch (e) { s = ''; } }
    var p = new URLSearchParams(s);
    if (p.get('from')) fromCombo.set(cityByCode(p.get('from').toUpperCase()));
    if (p.get('to')) toCombo.set(cityByCode(p.get('to').toUpperCase()));
    if (p.get('stops') === '2') setStops(2);
    var d = $('detour');
    if ([].some.call(d.options, function (o) { return o.value === p.get('detour'); })) d.value = p.get('detour');
    state.detour = +d.value;
  }

  window.addEventListener('resize', function () { applyView(); });

  buildMap();
  applyView();
  readState();
  render();

  /* If the page and this script came from different deploys, the browser is
     holding a stale copy of one of them. Say so and offer a clean reload. */
  function checkBuild() {
    var bad = !window.FSO_DATA || !window.FSO_MAP || (window.FSO_BUILD && window.FSO_BUILD !== BUILD);
    if (!bad) return;
    var bar = document.createElement('div');
    bar.className = 'alert';
    bar.innerHTML = 'This page and its files are from different versions of the app, so it may not work properly.<br>' +
      '<button type="button">Reload the app</button>';
    bar.querySelector('button').addEventListener('click', function () { location.reload(); });
    var c = document.querySelector('.controls');
    if (c) c.insertBefore(bar, c.firstChild);
  }
})();
